import * as electron from 'electron'

const electronModule = (electron as any).default ?? electron
const { contextBridge, ipcRenderer } = electronModule

contextBridge.exposeInMainWorld('api', {
  selectFolder: () => ipcRenderer.invoke('select-folder'),
  scanFiles: (folderPath: string, options?: Record<string, unknown>) => ipcRenderer.invoke('scan-files', folderPath, options),
  analyzeDuplicates: (files: any[], options?: Record<string, unknown>) => ipcRenderer.invoke('analyze-duplicates', files, options),
  executePlan: (plan: any) => ipcRenderer.invoke('execute-plan', plan),
  revealInFinder: (targetPath: string) => ipcRenderer.invoke('reveal-in-finder', targetPath),
  openExternal: (url: string) => ipcRenderer.invoke('open-external', url),
  openReportFolder: (reportPath: string) => ipcRenderer.invoke('open-report-folder', reportPath),
  getActivity: (limit?: number) => ipcRenderer.invoke('activity:getRecent', limit),
  clearActivity: () => ipcRenderer.invoke('activity:clear'),
  addTestActivity: () => ipcRenderer.invoke('activity:addTestEntry'),
  restoreToHistory: (operationId: string) => ipcRenderer.invoke('activity:restoreTo', operationId),
  canUndo: () => ipcRenderer.invoke('activity:canUndo'),
  undoLastMove: () => ipcRenderer.invoke('activity:undoLastMove'),
  getDashboardStats: () => ipcRenderer.invoke('dashboard:getStats'),
  getAutomationMode: () => ipcRenderer.invoke('automation:getMode'),
  setAutomationMode: (mode: 'auto' | 'review') => ipcRenderer.invoke('automation:setMode', mode),
  listReviewQueue: () => ipcRenderer.invoke('automation:listQueue'),
  enqueueProposedActions: (actions: any[]) => ipcRenderer.invoke('automation:enqueueProposedActions', actions),
  listRules: () => ipcRenderer.invoke('automation:listRules'),
  saveRules: (rules: any[]) => ipcRenderer.invoke('automation:saveRules', rules),
  getSettings: () => ipcRenderer.invoke('automation:getSettings'),
  saveSettings: (settings: any) => ipcRenderer.invoke('automation:saveSettings', settings),
  listArchiveItems: () => ipcRenderer.invoke('archive:list'),
  restoreArchiveItem: (itemId: string) => ipcRenderer.invoke('archive:restore', itemId),
  resolveFolderTarget: (basePath: string, folderName: string) => ipcRenderer.invoke('folders:resolveTarget', basePath, folderName),
  listCreatedFolders: () => ipcRenderer.invoke('folders:listCreated'),
  updateCreatedFolder: (itemId: string, updates: any) => ipcRenderer.invoke('folders:updateMeta', itemId, updates),
  renameCreatedFolder: (itemId: string, nextName: string) => ipcRenderer.invoke('folders:rename', itemId, nextName),
  openPath: (targetPath: string) => ipcRenderer.invoke('files:open', targetPath),
  selectFile: () => ipcRenderer.invoke('files:select'),
  applyProposedAction: (actionId: string) => ipcRenderer.invoke('automation:apply', actionId),
  rejectProposedAction: (actionId: string) => ipcRenderer.invoke('automation:reject', actionId),
  startDesktopWatcher: () => ipcRenderer.invoke('desktop-watcher:start'),
  stopDesktopWatcher: () => ipcRenderer.invoke('desktop-watcher:stop'),
  getDesktopWatcherStatus: () => ipcRenderer.invoke('desktop-watcher:status'),
  startDownloadsWatcher: () => ipcRenderer.invoke('downloads-watcher:start'),
  stopDownloadsWatcher: () => ipcRenderer.invoke('downloads-watcher:stop'),
  getDownloadsWatcherStatus: () => ipcRenderer.invoke('downloads-watcher:status'),
  getSystemInfo: () => ipcRenderer.invoke('system:getInfo'),
  getScanConfig: () => ipcRenderer.invoke('scan:getConfig'),
  createSandbox: () => ipcRenderer.invoke('sandbox:create'),
  resetSandbox: () => ipcRenderer.invoke('sandbox:reset'),
  openSandboxFolder: () => ipcRenderer.invoke('sandbox:open')
})
